USE Mangata_Gallo;
SHOW COLUMNS FROM Staff;
ALTER TABLE Staff
MODIFY FullName VARCHAR(150) NULL;
ALTER TABLE Staff
ADD COLUMN GENDER VARCHAR(10) default 'Male';
ALTER TABLE Staff
DROP COLUMN GENDER;
CREATE TABLE Machinery (
    EmployeeID VARCHAR(10),
    FullName VARCHAR(100),
    County VARCHAR(100),
    PhoneNumber INT
);
ALTER TABLE Machinery
MODIFY COLUMN EmployeeID VARCHAR(10) NOT NULL PRIMARY KEY,MODIFY FullName varchar(100) NOT NULL,MODIFY County VARCHAR(100) NOT NULL
,MODIFY PhoneNumber INT NOT NULL;
ALTER TABLE Machinery ADD COLUMN age INT CHECK(age>18);
SHOW COLUMNS FROM Machinery;