CREATE DATABASE Mangata_Gallo;
USE Mangata_Gallo; 
CREATE TABLE clients(ClientID INT NOT NULL PRIMARY KEY,FullName VARCHAR(50) NOT NULL, PhoneNumber INT NOT NULL UNIQUE);
SHOW COLUMNS FROM clients;
CREATE TABLE Items(ItemID INT NOT NULL PRIMARY KEY,ItemName varchar(100) NOT NULL, Price DECIMAL(5,2) NOT NULL);
SHOW COLUMNS FROM Items;
CREATE TABLE Orders(OrderID INT NOT NULL PRIMARY KEY,ClientID int not null,FOREIGN KEY (ClientID) references clients(ClientID),ItemID INT NOT NULL,
FOREIGN KEY (ItemID) REFERENCES Items(ItemID),Quantity INT NOT NULL CHECK(Quantity<=3),COST DECIMAL(6,2) NOT NULL );
SHOW COLUMNS FROM Orders;