USE little_lemon;
SHOW COLUMNS FROM customers;
CREATE TABLE Customers1 (CustomerID INT NOT NULL PRIMARY KEY,fullname VARCHAR(50),PHONENUMBER int NOT NULL UNIQUE );
SHOW COLUMNS FROM Customers1;
SHOW COLUMNS FROM BOOKINGS;
CREATE TABLE Bookings1(BookingID INT NOT NULL PRIMARY KEY,BookingDate DATE NOT NULL,TableNumber INT NOT NULL,NumberOfGuests INT NOT NULL CHECK(NumberOfGuests<=8)
,CustomerID INT NOT NULL
,FOREIGN KEY (CustomerID) REFERENCES Customers1(CustomerID) ON DELETE CASCADE ON UPDATE CASCADE );
SHOW COLUMNS FROM Bookings1;